
spring:
  application:
    name: producer
server:
  port: 8763
eureka:
  instance:
    register:
      hostname: localhost
      port: 8762
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.register.hostname}:${eureka.instance.register.port}/eureka/
